
# PERFIL DE EXECUÇÃO DE DESENVOLVIMENTO

spring:
  datasource:
    url: jdbc:h2:mem:sdw2023 #indicando que quer um banco de dados H2 e mem indica que o nome será sdw2023
    username: sdw2023
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true
  h2: #condigurações do H2
    console:
      enabled: true
      path: /h2-console #Essa linha indica que poderemos acessar o banco via browser
      settings:
        trace: false
        web-allow-others: false